package com.k2.schemas.worklist.d1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-000281-redhat-3
 * 2019-09-04T23:17:17.892+08:00
 * Generated source version: 3.1.11.fuse-000281-redhat-3
 * 
 */
@WebService(targetNamespace = "http://schemas.k2.com/worklist/d1", name = "WSHttpGet")
@XmlSeeAlso({com.k2.schemas.event.d1.ObjectFactory.class, ObjectFactory.class, com.k2.schemas.activity.d1.ObjectFactory.class, com.k2.schemas.process.d1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WSHttpGet {

    @WebMethod(operationName = "OpenProcessInstance")
    @WebResult(name = "ProcessInstance", targetNamespace = "http://schemas.k2.com/worklist/d1", partName = "Body")
    public ProcessInstance openProcessInstance(
        @WebParam(partName = "ProcInstID", name = "ProcInstID", targetNamespace = "")
        java.lang.String procInstID
    );

    @WebMethod(operationName = "ReleaseWorklistItem")
    public void releaseWorklistItem(
        @WebParam(partName = "Serial", name = "Serial", targetNamespace = "")
        java.lang.String serial
    );

    @WebMethod(operationName = "OpenWorklistItem")
    @WebResult(name = "WorklistItem", targetNamespace = "http://schemas.k2.com/worklist/d1", partName = "Body")
    public WorklistItem openWorklistItem(
        @WebParam(partName = "Serial", name = "Serial", targetNamespace = "")
        java.lang.String serial,
        @WebParam(partName = "Sync", name = "Sync", targetNamespace = "")
        java.lang.String sync
    );

    @WebMethod(operationName = "StartNewProcessInstanceScalar")
    @WebResult(name = "long", targetNamespace = "http://schemas.k2.com/worklist/d1", partName = "Body")
    public long startNewProcessInstanceScalar(
        @WebParam(partName = "ProcessFullName", name = "ProcessFullName", targetNamespace = "")
        java.lang.String processFullName,
        @WebParam(partName = "Folio", name = "Folio", targetNamespace = "")
        java.lang.String folio,
        @WebParam(partName = "Sync", name = "Sync", targetNamespace = "")
        java.lang.String sync
    );

    @WebMethod(operationName = "ExecuteActionBySerial")
    public void executeActionBySerial(
        @WebParam(partName = "Serial", name = "Serial", targetNamespace = "")
        java.lang.String serial,
        @WebParam(partName = "Action", name = "Action", targetNamespace = "")
        java.lang.String action,
        @WebParam(partName = "Sync", name = "Sync", targetNamespace = "")
        java.lang.String sync
    );

    @WebMethod(operationName = "OpenWorklist")
    @WebResult(name = "WorklistItemCollection", targetNamespace = "http://schemas.k2.com/worklist/d1", partName = "Body")
    public ArrayOfWorklistItem openWorklist(
        @WebParam(partName = "IncludeData", name = "IncludeData", targetNamespace = "")
        java.lang.String includeData
    );
}
