package com.k2.schemas.worklist.d1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11.fuse-000281-redhat-3
 * 2019-09-04T23:18:50.603+08:00
 * Generated source version: 3.1.11.fuse-000281-redhat-3
 * 
 */
@WebService(targetNamespace = "http://schemas.k2.com/worklist/d1", name = "WSSoap")
@XmlSeeAlso({com.k2.schemas.event.d1.ObjectFactory.class, ObjectFactory.class, com.k2.schemas.activity.d1.ObjectFactory.class, com.k2.schemas.process.d1.ObjectFactory.class})
public interface WSSoap {

    @WebMethod(operationName = "OpenProcessInstance", action = "http://schemas.k2.com/worklist/d1/OpenProcessInstance")
    @RequestWrapper(localName = "OpenProcessInstance", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.OpenProcessInstance")
    @ResponseWrapper(localName = "OpenProcessInstanceResponse", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.OpenProcessInstanceResponse")
    @WebResult(name = "ProcessInstance", targetNamespace = "http://schemas.k2.com/worklist/d1")
    public com.k2.schemas.worklist.d1.ProcessInstance openProcessInstance(
        @WebParam(name = "ProcInstID", targetNamespace = "http://schemas.k2.com/worklist/d1")
        long procInstID
    );

    @WebMethod(operationName = "ExecuteActionByWorklistItem", action = "http://schemas.k2.com/worklist/d1/ExecuteActionByWorklistItem")
    @RequestWrapper(localName = "ExecuteActionByWorklistItem", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.ExecuteActionByWorklistItem")
    @ResponseWrapper(localName = "ExecuteActionByWorklistItemResponse", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.ExecuteActionByWorklistItemResponse")
    public void executeActionByWorklistItem(
        @WebParam(name = "WorklistItem", targetNamespace = "http://schemas.k2.com/worklist/d1")
        com.k2.schemas.worklist.d1.WorklistItem worklistItem,
        @WebParam(name = "Action", targetNamespace = "http://schemas.k2.com/worklist/d1")
        java.lang.String action,
        @WebParam(name = "Sync", targetNamespace = "http://schemas.k2.com/worklist/d1")
        boolean sync
    );

    @WebMethod(operationName = "ReleaseWorklistItem", action = "http://schemas.k2.com/worklist/d1/ReleaseWorklistItem")
    @RequestWrapper(localName = "ReleaseWorklistItem", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.ReleaseWorklistItem")
    @ResponseWrapper(localName = "ReleaseWorklistItemResponse", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.ReleaseWorklistItemResponse")
    public void releaseWorklistItem(
        @WebParam(name = "Serial", targetNamespace = "http://schemas.k2.com/worklist/d1")
        java.lang.String serial
    );

    @WebMethod(operationName = "UpdateProcessInstance", action = "http://schemas.k2.com/worklist/d1/UpdateProcessInstance")
    @RequestWrapper(localName = "UpdateProcessInstance", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.UpdateProcessInstance")
    @ResponseWrapper(localName = "UpdateProcessInstanceResponse", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.UpdateProcessInstanceResponse")
    public void updateProcessInstance(
        @WebParam(name = "ProcessInstance", targetNamespace = "http://schemas.k2.com/worklist/d1")
        com.k2.schemas.worklist.d1.ProcessInstance processInstance,
        @WebParam(name = "Sync", targetNamespace = "http://schemas.k2.com/worklist/d1")
        boolean sync
    );

    @WebMethod(operationName = "StartNewProcessInstance", action = "http://schemas.k2.com/worklist/d1/StartNewProcessInstance")
    @RequestWrapper(localName = "StartNewProcessInstance", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.StartNewProcessInstance")
    @ResponseWrapper(localName = "StartNewProcessInstanceResponse", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.StartNewProcessInstanceResponse")
    public void startNewProcessInstance(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ProcessInstance", targetNamespace = "http://schemas.k2.com/worklist/d1")
        javax.xml.ws.Holder<ProcessInstance> processInstance,
        @WebParam(name = "Sync", targetNamespace = "http://schemas.k2.com/worklist/d1")
        boolean sync
    );

    @WebMethod(operationName = "OpenWorklistItem", action = "http://schemas.k2.com/worklist/d1/OpenWorklistItem")
    @RequestWrapper(localName = "OpenWorklistItem", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.OpenWorklistItem")
    @ResponseWrapper(localName = "OpenWorklistItemResponse", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.OpenWorklistItemResponse")
    @WebResult(name = "WorklistItem", targetNamespace = "http://schemas.k2.com/worklist/d1")
    public com.k2.schemas.worklist.d1.WorklistItem openWorklistItem(
        @WebParam(name = "Serial", targetNamespace = "http://schemas.k2.com/worklist/d1")
        java.lang.String serial,
        @WebParam(name = "Sync", targetNamespace = "http://schemas.k2.com/worklist/d1")
        boolean sync
    );

    @WebMethod(operationName = "StartNewProcessInstanceScalar", action = "http://schemas.k2.com/worklist/d1/StartNewProcessInstanceScalar")
    @RequestWrapper(localName = "StartNewProcessInstanceScalar", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.StartNewProcessInstanceScalar")
    @ResponseWrapper(localName = "StartNewProcessInstanceScalarResponse", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.StartNewProcessInstanceScalarResponse")
    @WebResult(name = "StartNewProcessInstanceScalarResult", targetNamespace = "http://schemas.k2.com/worklist/d1")
    public long startNewProcessInstanceScalar(
    		/*
        @WebParam(name = "ProcessFullName", targetNamespace = "http://schemas.k2.com/worklist/d1")
        java.lang.String processFullName,
        @WebParam(name = "Folio", targetNamespace = "http://schemas.k2.com/worklist/d1")
        java.lang.String folio,
        @WebParam(name = "Sync", targetNamespace = "http://schemas.k2.com/worklist/d1")
        boolean sync
        */
        @WebParam(name = "arg0", targetNamespace = "http://schemas.k2.com/worklist/d1")
        StartNewProcessInstanceScalar arg0
    );

    @WebMethod(operationName = "ExecuteActionBySerial", action = "http://schemas.k2.com/worklist/d1/ExecuteActionBySerial")
    @RequestWrapper(localName = "ExecuteActionBySerial", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.ExecuteActionBySerial")
    @ResponseWrapper(localName = "ExecuteActionBySerialResponse", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.ExecuteActionBySerialResponse")
    @WebResult(name = "ExecuteActionBySerialResult", targetNamespace = "http://schemas.k2.com/worklist/d1")
    public void executeActionBySerial(
    	/*	
        @WebParam(name = "Serial", targetNamespace = "http://schemas.k2.com/worklist/d1")
        java.lang.String serial,
        @WebParam(name = "Action", targetNamespace = "http://schemas.k2.com/worklist/d1")
        java.lang.String action,
        @WebParam(name = "Sync", targetNamespace = "http://schemas.k2.com/worklist/d1")
        boolean sync
        */
    		 @WebParam(name = "arg0", targetNamespace = "http://schemas.k2.com/worklist/d1")
    		ExecuteActionBySerial arg0
    );

    @WebMethod(operationName = "OpenWorklist", action = "http://schemas.k2.com/worklist/d1/OpenWorklist")
    @RequestWrapper(localName = "OpenWorklist", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.OpenWorklist")
    @ResponseWrapper(localName = "OpenWorklistResponse", targetNamespace = "http://schemas.k2.com/worklist/d1", className = "com.k2.schemas.worklist.d1.OpenWorklistResponse")
    @WebResult(name = "OpenWorklistResult", targetNamespace = "http://schemas.k2.com/worklist/d1")
    public com.k2.schemas.worklist.d1.ArrayOfWorklistItem openWorklist(
    		/*
        @WebParam(name = "IncludeData", targetNamespace = "http://schemas.k2.com/worklist/d1")
        boolean includeData
        */
        @WebParam(name = "arg0", targetNamespace = "http://schemas.k2.com/worklist/d1")
        OpenWorklist arg0
    );
}
